name = "cgq"
version = "1.0.0"

description = ""
licences = ["MIT"]
repository = { type = "github", user = "STASER-Lab", repo = "cgq" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_httpc = ">= 4.0.0 and < 5.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
birl = ">= 1.8.0 and < 2.0.0"
clip = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
trellis = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
